spring:
  main:
    banner-mode: log
  profiles:
    active: ${ENV_PROFILE:local}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      jdbc:
        time_zone: UTC
    show-sql: ${SHOW_SQL:false}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
#    url: ${AZURE_POSTGRESQL_CONNECTIONSTRING:jdbc:postgresql://library-manager-server.postgres.database.azure.com:5432/library-manager-database?sslmode=require&user=vcyiuuevid&password=2Y36021744LE6YIO%24}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/library-manager}
    username: ${DATABASE_USERNAME:library-manager}
    password: ${DATABASE_PASSWORD:library-manager}
    hikari:
      pool-name: library-manager-connection-pool
      maximum-pool-size: ${DATABASE_POOL_SIZE:10}
  mvc:
    problemdetails:
      enabled: true


springdoc:
  enable-native-support: true
  show-login-endpoint: true

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${PORT:8080}
  cors-origins: ${CORS_ORIGINS:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET:ff448f84-686c-47fc-a563-432711006f5a}