CREATE TABLE book
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    register_number   INTEGER,
    registration_date date,
    title             VARCHAR(255),
    volume            VARCHAR(255),
    copy              VARCHAR(255),
    location          VARCHAR(255),
    publisher_id      BIGINT,
    publication_year  INTEGER,
    acquisition_form  VARCHAR(255),
    index             VARCHAR(255),
    cdd               VARCHAR(255),
    observation       TEXT,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_register_number UNIQUE (register_number);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_PUBLISHER FOREIGN KEY (publisher_id) REFERENCES publisher (id);

CREATE TABLE books_authors
(
    book_id    BIGINT NOT NULL,
    author_id BIGINT NOT NULL
);

ALTER TABLE books_authors
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE books_authors
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES book (id);