CREATE TABLE publisher
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_publisher PRIMARY KEY (id)
);

CREATE INDEX idx_publisher_name ON publisher (name);
