CREATE TABLE lending
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    book_id     BIGINT,
    return_date date,
    returned_at date,
    created_at  date,
    CONSTRAINT pk_lending PRIMARY KEY (id)
);

CREATE INDEX idx_lending_user_id ON lending (user_id);
CREATE INDEX idx_lending_book_id ON lending (book_id);

ALTER TABLE lending
    ADD CONSTRAINT FK_LENDING_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE lending
    ADD CONSTRAINT FK_LENDING_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

--alter table book add column lending_id bigint;
--alter table book add constraint FK_BOOK_ON_LENDING foreign key (lending_id) references lending (id);
ALTER TABLE book
    ADD COLUMN lending_id BIGINT;
ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_LENDING FOREIGN KEY (lending_id) REFERENCES lending (id);
