CREATE TABLE profile
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    document    VARCHAR(255),
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD COLUMN profile_id BIGINT;
ALTER TABLE "user"
    ADD CONSTRAINT fk_user_profile FOREIGN KEY (profile_id) REFERENCES profile (id);
ALTER TABLE "user"
    ADD COLUMN active BOOLEAN DEFAULT TRUE;
